// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");

@test:Config {}
isolated function  testDelete-/crm/v3/objects/meetings/{meetingId}_archive() {

}

@test:Config {}
isolated function  testPatch-/crm/v3/objects/meetings/{meetingId}_update() {
}

@test:Config {}
isolated function  testGet-/crm/v3/objects/meetings/{meetingId}_getById() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/batch/update_update() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/batch/read_read() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/batch/archive_archive() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings_create() {
}

@test:Config {}
isolated function  testGet-/crm/v3/objects/meetings_getPage() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/batch/upsert_upsert() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/batch/create_create() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/meetings/search_doSearch() {
}
