{
    "openapi": "3.0.1",
    "info": {
        "title": "Meetings",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "If you're using a different service outside of HubSpot to schedule your meetings, or if you want to supplement the built-in tracking of the HubSpot meetings tool, you can use this API to help keep track of how your meetings went with prospects and customers in the HubSpot CRM.",
        "x-hubspot-related-documentation": [
            {
                "name": "Meetings Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/meetings"
            }
        ],
        "x-hubspot-introduction": "The meetings engagements API allows you to log and manage meetings on the corresponding CRM records, such as contacts or companies. You can include notes from the meeting and its outcome, along with other important data from the meeting to share with the rest of your team."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/meetings"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read a batch of meetings",
                "operationId": "post-/crm/v3/objects/meetings/batch/read_read",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ],
                "description": "Returns a batch of meeting records matching the provided internal IDs or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/{meetingId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a meeting by ID",
                "description": "Read an Object identified by `{meetingId}`. `{meetingId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/meetings/{meetingId}_getById",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a meeting by ID",
                "description": "Move an Object identified by `{meetingId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/meetings/{meetingId}_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Partially update a meeting",
                "description": "Perform a partial update of an Object identified by `{meetingId}`. `{meetingId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/meetings/{meetingId}_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of meetings by ID",
                "operationId": "post-/crm/v3/objects/meetings/batch/archive_archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ],
                "description": "Archives the specified meetings by ID. Returns no content on success."
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of meetings",
                "operationId": "post-/crm/v3/objects/meetings/batch/create_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ],
                "description": "Returns the created meeting records, with partial success details provided in a 207 response."
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of meetings",
                "operationId": "post-/crm/v3/objects/meetings/batch/update_update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ],
                "description": "Returns the updated batch of meeting objects, including any partial success details for multi-status responses."
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "List a page of meetings",
                "description": "Read a page of meetings. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/meetings_getPage",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a meeting",
                "description": "Create a meeting with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard meetings is provided.",
                "operationId": "post-/crm/v3/objects/meetings_create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of meetings",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/meetings/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.write"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/crm/v3/objects/meetings/search_doSearch",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.contacts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.contacts.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "description": "Returns a paginated list of meeting objects matching the specified search criteria and filters.",
                "summary": "Search for meetings"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}