[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.engagement.meeting"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "meeting"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.engagement.meeting"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
